### PR TITLE
Order name when create user

### PR DESCRIPTION
**Pull request by dthtien**

### CODE REVIEW

**Comment by fongfan999** [comment]
image
Why didn't you use `first_name` and `last_name` from `request.env["omniauth.auth"]` @dthtien

**Comment by dthtien** [comment]
I have already fixed it

**Comment by fongfan999** [comment]
Good job. Can you replace all `ordered_name` to `full_name` methods.

**Comment by dthtien** [comment]
I have replaced all ordered_name at the last commit

**Comment by fongfan999** [comment]
OK, nice!!

**Pull request merged**
