### PR TITLE
Please check and tell me what i should do. tks

### PR DESCRIPTION
**Pull request by dthtien**

### CODE REVIEW

**Comment by fongfan999** [comment]
Alright! It would be nice if you tell me what you did on the **`Title`** and **`Description`** in subsequent pull requests.

**Comment by fongfan999** [comment]
- [ ] Can we remove these 3 lines. I think we don't need them anymore.

```ruby
ActiveSupport::Inflector.inflections do |inflect|
  inflect.plural 'answer', 'answers'
end
```

- [ ] Why did you separate into 2 `actions`? Could you explain that?
```ruby
before_action :set_question, only: [:upvote_question, :downvote_question]
before_action :set_question_vote,  only: [:upvote_question, :downvote_question]
# ....


private
  def set_question
    @question = Question.find(params[:question_id])
    authorize @question, :create?
  end

  def set_question_vote
    @vote = Vote.create_vote(@question, current_user)
  end

  # ...
```
But I think It would be better if you put this line 
```ruby
where(user: user, votable: record).first_or_create
```
in your **`change_vote`** method. And this method could be something like this:
```ruby
# models/user.rb
def change_vote(votable, type = :up)
  vote = Vote.where(user: self, votable: votable).first_or_create
  vote.send "#{type}!"
end
```
I thought: `User` **change** `Vote` is more readable than `Vote` **is changed** by `User`

**Comment by dthtien** [comment]
## Tks for comment, it's helpful.
1. "Can we remove this 3 lines. I think we don't need them anymore". 
I removed it.
2.  "Why did you separate into 2 actions? Could you explain that?"
Actually, I should put them to just one method last night but I forgot that, Tks for remind me.
3. "But I think It would be better if you put this line
_where(user: user, votable: record).first_or_create_ 
in your change_vote method. And this method could be something like this:" 
That is great idea, Many thanks. ^^

**Comment by fongfan999** [comment]
Everything is very good 💯 . But there was some issues in the last commit.

1. Please send another pull request things that they're **not** concerned with this pull request.
2. In the **`time_in_words(time)`** method, It may return something like: 
`khoảng 1 phút trước` ($1) or `01 Tháng một, 2001 lúc 01:01` ($2).
So $2 is not **`in words`**, the method name doesn't reflect the result. I think you should rename this method to `display_time(time)`, `format_time(time)` or whatever you want.
3. Inside this method:
- You should you `Time.zone.now` instead of `Time.now` cause the database is stored at `UTC+0`
- I think this is the better way:
```ruby
from_time = (Time.now - time)/1.day
if from_time >= 2
# ...

# ---------------

if (Time.zone.now - time) > 1.day
# ...
```
- We shouldn't change `vi.yml` file. Use `strftime` instead.
```yaml
formats:
  default: "%a, %d %b %Y %H:%M:%S %z"
  long: "%d %B, %Y lúc %H:%M"
  short: "%d %b lúc %H:%M"
```
#### The final method could be:
```ruby
def display_time(time)
  if (Time.zone.now - time) > 1.day
    time.strftime "%d %B, %Y lúc %H:%M"
  else
    "#{time_ago_in_words(time)} trước"
  end
end
```

**Comment by dthtien** [comment]
But when I used **_time.strftime "%d %B, %Y lúc %H:%M"_**  it was displayed like **_19 April, 2017 lúc 09:11_**

**Comment by fongfan999** [comment]
Oh I forgot. Use the l (alias for localize) method instead of raw strftime, like this: 
```ruby
l(time, format: '%B %d, in the year %Y')
```

**Comment by dthtien** [comment]
Great. many thanks.
Why do you sleep so late?

**Pull request merged**
