### PR TITLE
Please check and tell me what I should do. tks

### PR DESCRIPTION
**Pull request by dthtien**

### CODE REVIEW

**Comment by fongfan999** [comment]
Could you send just once a pull request for each commit.

- [ ]  Don't use ~`@group.patron_id == current_user`~, use `@group.patron == current_user` or `@group.patron_id == current_user.id` instead.
```ruby
def authorization_patron
  unless @group.patron_id == current_user
    flash[:alert] = "Chỉ có partron mới được chỉnh sửa" 
    redirect_to @group
  end
end
```
- [ ] `Unauthorized user` can access this `@question`. Eg: `group (id = 1)`, this `group` has a `question (id = 1)`. So, the path will be `/groups/1/questions/1`. And of course, any `authenticated user` can access that path and get the `@question`
```ruby
def show
  @question = @group.questions.find(params[:id])
end

private
  # ...

  def set_question
    @question = @group.questions.find(params[:id])
  end
```

- [ ] Naming `before_action` as a `verb` and fix `typos` also, please.
```ruby
  before_action :patron_or_own_authorizetion, only: :destroy
```
- [ ] **DO NOT** use `unless` in the statement that have more than one `condition`. It would make other people confused, of course include me.
```ruby
def patron_or_own_authorizetion
  @question = @group.questions.find(params[:id])
  unless @question.user == current_user || @group.patron == current_user
    flash[:alert] =  "Bạn không có quyền xóa câu hỏi."
    redirect_to @group
  end
end
```

Again, you send just once a pull request for each commit.

**Comment by dthtien** [comment]
## Tks for your comment. It's very helpful
-  " _The unauthorized user can access this @question. Eg: group (id = 1), this group has a question (id = 1). So, the path will be /groups/1/questions/1. And of course, any authenticated user can access that path and get the @question". An unauthorized user can not access @question because  I have already
 defined **_before_action_** method **_set_group_** 
**def set_group
      @group = current_user.groups.find(params[:group_id])
end** 
So an authorize user can not asset @quetion.

- I'm sorry about these bugs and I'll fix these soon

**Comment by dthtien** [comment]
## Tks for your comment. It's very helpful
-  " _The unauthorized user can access this @question. Eg: group (id = 1), this group has a question (id = 1). So, the path will be /groups/1/questions/1. And of course, any authenticated user can access that path and get the @question".
 An unauthorized user can not access @question because  I have already defined **_before_action_** method **_set_group_** 
**def set_group
      @group = current_user.groups.find(params[:group_id])
end** 
So an authorize user can not asset @quetion.

- I'm sorry about these bugs and I'll fix these soon

**Comment by fongfan999** [comment]
Everything is getting complicated in authorization. I'm gonna use [Pundit](https://github.com/elabs/pundit) gem for `DRYing up code`  in the distant future. You can refer to the [documents](https://github.com/elabs/pundit) familiar with the app.

**Comment by dthtien** [comment]
Ok. I'll read it when I'm at home. 
See you three days later and Say a long time no see. :)

**Pull request merged**
